define(function () {
    'use strict'
    return {

        MARKUP_TYPE_ARROW: "arrow",
        MARKUP_TYPE_TEXT: "label",
        MARKUP_TYPE_RECTANGLE: "rectangle",
        MARKUP_TYPE_CIRCLE: "ellipse",
        MARKUP_TYPE_CLOUD: "cloud",
        MARKUP_TYPE_FREEHAND: "freehand",
        MARKUP_TYPE_POLYLINE: "polyline",
        MARKUP_TYPE_POLYCLOUD: "polycloud",
        EVENT_EDITMODE_CHANGED: "EVENT_EDITMODE_CHANGED",
        EVENT_EDITMODE_ENTER: "EVENT_EDITMODE_ENTER",
        EVENT_EDITMODE_LEAVE: "EVENT_EDITMODE_LEAVE",

        EVENT_MARKUP_SELECTED: "EVENT_MARKUP_SELECTED",
        EVENT_MARKUP_DRAGGING: "EVENT_MARKUP_DRAGGING",
        EVENT_MARKUP_ENTER_EDITION: "EVENT_MARKUP_ENTER_EDITION",
        EVENT_MARKUP_CANCEL_EDITION: "EVENT_MARKUP_CANCEL_EDITION",
        EVENT_MARKUP_DELETE_EDITION: "EVENT_MARKUP_DELETE_EDITION",

        EVENT_EDITMODE_CREATION_BEGIN: "EVENT_EDITMODE_CREATION_BEGIN",
        EVENT_EDITMODE_CREATION_END: "EVENT_EDITMODE_CREATION_END",
        EVENT_MARKUP_DESELECT: "EVENT_MARKUP_DESELECT",

        EVENT_EDITFRAME_EDITION_START: "EVENT_EDITFRAME_EDITION_START",
        EVENT_EDITFRAME_EDITION_END: "EVENT_EDITFRAME_EDITION_END",

        EVENT_ENTER_EDIT_MODE: "EVENT_MARKUP_CORE_ENTER_EDIT_MODE",
        EVENT_LEAVE_EDIT_MODE: "EVENT_MARKUP_CORE_LEAVE_EDIT_MODE",
        EVENT_SELECTION_CHANGED: "EVENT_MARKUP_SELECTION_CHANGED",

    }
});